name: Publish NuGet Package

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x' # Adjust the version as needed

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --configuration Release --no-restore

    - name: Pack the NuGet package
      run: dotnet pack --configuration Release --no-build --output ./nupkg

    - name: Publish NuGet package
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
       --skip-duplicate

    - name: Fetch existing README
      run: |
        if [ -f README.md ]; then
          echo "Existing README found."
        else
          curl -o README.md https://raw.shoesheill.com/${{ github.repository }}/main/README.md
        fi

    - name: Update README
      run: |
        echo "## Release Notes" >> README.md
        echo "### Version ${{ github.ref_name }}" >> README.md
        echo "Released on ${{ github.event.push.head_commit.timestamp }}" >> README.md
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add README.md
        git commit -m "Update README for version ${{ github.ref_name }}"
        git push
